# fly.toml file generated for sandman-simple-server on 2022-11-10T14:42:15-05:00

app = "sandman-simple-server"

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"

[[services]]
  internal_port = 3000
  protocol = "tcp"
